// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRWQrc8e8x9c6_J2JhEeEmqieu_KPm2Ic',
    appId: '1:632847018782:web:5730b34e1ea3e253d5770f',
    messagingSenderId: '632847018782',
    projectId: 'food-delivery-50d34',
    authDomain: 'food-delivery-50d34.firebaseapp.com',
    storageBucket: 'food-delivery-50d34.appspot.com',
    measurementId: 'G-SQKYJ27R5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuoj2tNc9-34wBvs7mpkDoHI8capoZhaw',
    appId: '1:632847018782:android:456210c8e5db8adad5770f',
    messagingSenderId: '632847018782',
    projectId: 'food-delivery-50d34',
    storageBucket: 'food-delivery-50d34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1FuJbz_pq_0p_TJ3JlE23k2bhaB8Qjog',
    appId: '1:632847018782:ios:048b4e0d220011bdd5770f',
    messagingSenderId: '632847018782',
    projectId: 'food-delivery-50d34',
    storageBucket: 'food-delivery-50d34.appspot.com',
    iosClientId: '632847018782-vatcmf5mh7l8u4jdhcukk2kpnfgg6mij.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1FuJbz_pq_0p_TJ3JlE23k2bhaB8Qjog',
    appId: '1:632847018782:ios:048b4e0d220011bdd5770f',
    messagingSenderId: '632847018782',
    projectId: 'food-delivery-50d34',
    storageBucket: 'food-delivery-50d34.appspot.com',
    iosClientId: '632847018782-vatcmf5mh7l8u4jdhcukk2kpnfgg6mij.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapp',
  );
}
